<a href="https://colab.research.google.com/github/Asuskf/tensorflow1.x/blob/main/scripts/intro/04_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
#!pip install tensorflow==1.14
%tensorflow_version 1.x
import numpy as np
import tensorflow as tf
print(tf.__version__)

1.15.2


## Cómo trabajar con matrices


In [2]:
session = tf.Session()

### 1. Cómo crear mactrices

In [22]:
identity = tf.diag([1., 1., 1., 1.])
print(session.run(identity))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
A = tf.truncated_normal([3, 4])
print(session.run(A))

[[-0.5655614   0.26749215  1.8319795   1.8368407 ]
 [-0.06653576 -0.11025794  0.7653535   0.4473987 ]
 [-1.1131717   0.7483441  -0.052915   -0.33911777]]


In [17]:
B = tf.fill([3, 4], 1988.)
print(session.run(B))

[[1988. 1988. 1988. 1988.]
 [1988. 1988. 1988. 1988.]
 [1988. 1988. 1988. 1988.]]


In [13]:
C = tf.random_uniform([4, 3])
print(session.run(C))

[[0.31932366 0.63871753 0.18426776]
 [0.7483454  0.49268842 0.01332593]
 [0.8648361  0.2488364  0.23892522]
 [0.77341115 0.3161173  0.04193199]]


In [12]:
data = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9]])
D = tf.convert_to_tensor(data)
print(session.run(D))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### 2. Operar con matrices


In [18]:
print(session.run(A+B))

[[1989.1232 1988.8629 1987.3734 1987.9147]
 [1989.0311 1986.3004 1986.9943 1988.2441]
 [1989.2754 1987.7926 1989.1865 1986.6212]]


In [19]:
print(session.run(B-B))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
print(session.run(tf.matmul(A, C)))

[[-0.32509112 -0.34710845 -0.17103252]
 [-0.7028665  -1.3590957  -2.0380337 ]
 [-0.13352877 -0.851299   -0.22920215]]


In [23]:
print(session.run(tf.matmul(A, identity)))

[[-0.04317479  0.18542339 -0.3860934   1.0100802 ]
 [ 1.2851557   0.36101422 -0.81879973 -0.04744078]
 [-1.1484852   0.10882577 -0.93051416 -0.44386774]]


### 3. Transpuesta y determinante, inversa

In [24]:
print(session.run(tf.transpose(D)))

[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


In [25]:
print(session.run(tf.transpose(A)))

[[ 0.8526107   0.2912751  -1.1226834 ]
 [-1.9868896  -0.69619876  0.5876468 ]
 [ 0.5912135   1.0927222  -1.6409456 ]
 [ 0.23188202  0.5081153   0.8664435 ]]


In [26]:
print(session.run(tf.matrix_determinant(D)))

-9.51619735392994e-16


In [30]:
E = tf.convert_to_tensor(np.array([[1., 2., 3.], [-3., -6., -1], [0., 5, -3]]))
print(session.run(tf.matrix_determinant(E)))

-40.0


In [31]:
print(session.run(tf.matrix_inverse(D)))

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [32]:
print(session.run(tf.matrix_inverse(E)))

[[-5.75000000e-01 -5.25000000e-01 -4.00000000e-01]
 [ 2.25000000e-01  7.50000000e-02  2.00000000e-01]
 [ 3.75000000e-01  1.25000000e-01 -8.32667268e-18]]


### 4. Descomposución

In [33]:
print(session.run(tf.cholesky(identity)))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### 5. Valores y vectores propios

In [34]:
print(session.run(tf.self_adjoint_eigvals(E)))

[-10.24888536  -0.66882335   2.91770871]


In [35]:
print(session.run(tf.self_adjoint_eig(E)))

(array([-10.24888536,  -0.66882335,   2.91770871]), array([[ 0.21442787,  0.60489799, -0.76688924],
       [ 0.80402486,  0.3364893 ,  0.49022339],
       [-0.55458517,  0.72171557,  0.41420034]]))
