<a href="https://colab.research.google.com/github/Asuskf/tensorflow1.x/blob/main/scripts/intro/05_operaciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#!pip install tensorflow==1.14
%tensorflow_version 1.x
import numpy as np
import tensorflow as tf
print(tf.__version__)

TensorFlow 1.x selected.
1.15.2


In [ ]:
session = tf.Session()

### Operaciones aritméticas

In [ ]:
x = 3 
y = 4

In [ ]:
print(session.run(tf.add(x, y)))

7


In [ ]:
print(session.run(tf.multiply(x, y)))

12


In [ ]:
print(session.run(tf.div(x, y)))

Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
0


In [ ]:
print(session.run(tf.truediv(x, y)))

0.75


In [ ]:
print(session.run(tf.floor_div(7.0, 3.0)))

2.0


In [ ]:
print(session.run(tf.mod(23.0, 5.0)))

3.0


In [ ]:
print(session.run(tf.cross([1.0, 0., 0.], [0., 1., 0.])))

[0. 0. 1.]


### Funciones matemáticas

In [ ]:
x = [-3., -2. ,-1., 0., 1., 2.]

In [ ]:
print(session.run(tf.abs(x)))

[3. 2. 1. 0. 1. 2.]


In [ ]:
print(session.run(tf.ceil(6.4)))

7.0


In [ ]:
print(session.run(tf.floor(6.4)))

6.0


In [ ]:
print(session.run(tf.round(6.6)))

7.0


In [ ]:
print(session.run(tf.sin(x)))

[-0.14112    -0.9092974  -0.84147096  0.          0.84147096  0.9092974 ]


In [ ]:
print(session.run(tf.cos(x)))

[-0.9899925  -0.41614684  0.5403023   1.          0.5403023  -0.41614684]


In [ ]:
print(session.run(tf.tan(x)))

[ 0.14254655  2.1850398  -1.5574077   0.          1.5574077  -2.1850398 ]


In [ ]:
print(session.run(tf.exp(x)))

[0.04978707 0.13533528 0.36787945 1.         2.7182817  7.389056  ]


In [ ]:
print(session.run(tf.log(x)))

[      nan       nan       nan      -inf 0.        0.6931472]


In [ ]:
y = [3., 4., 7., -4., -3., 7.]

In [ ]:
print(session.run(tf.maximum(x, y)))

[3. 4. 7. 0. 1. 7.]


In [ ]:
print(session.run(tf.minimum(x, y)))

[-3. -2. -1. -4. -3.  2.]


In [ ]:
print(session.run(tf.negative(x)))

[ 3.  2.  1. -0. -1. -2.]


In [ ]:
print(session.run(tf.pow(x, y)))

[-27.  16.  -1.  inf   1. 128.]


In [ ]:
print(session.run(tf.sqrt(x)))

[      nan       nan       nan 0.        1.        1.4142135]


In [ ]:
print(session.run(tf.rsqrt(x)))

[       nan        nan        nan        inf 1.         0.70710677]


In [ ]:
print(session.run(tf.square(x)))

[9. 4. 1. 0. 1. 4.]


In [ ]:
print(session.run(tf.sign(x)))

[-1. -1. -1.  0.  1.  1.]


### Otras funciones

In [ ]:
print(session.run(tf.digamma(x)))

[       inf        inf        inf        inf -0.5772159  0.4227842]


In [ ]:
print(session.run(tf.lbeta(x)))

nan


In [ ]:
print(session.run(tf.lgamma(x)))

[inf inf inf inf  0.  0.]


In [ ]:
print(session.run(tf.erf(x)))

[-0.9999779 -0.9953223 -0.8427008  0.         0.8427008  0.9953223]


In [ ]:
print(session.run(tf.erfc(x)))

[1.999978   1.9953222  1.8427007  1.         0.1572992  0.00467773]


In [ ]:
print(session.run(tf.squared_difference(x, y)))

[36. 36. 64. 16. 16. 25.]


In [ ]:
print(session.run(tf.tan(3.1416/4.)))

1.0000036


### Funciones propias

$$ y = 5x^2 - 7x + 15 $$

In [ ]:
def custom_parabola(value):
    return tf.subtract(5 * tf.square(value), 7 * value) + 15
print(session.run(custom_parabola(5)))

105
